name: Add CFP
description: Add CFPs to the list by creating an issue 
title: "[Deadline: Date, Month]: Event Name City/Online"
labels: [open]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for adding the CFP and helping the community!
  - type: input
    id: Name
    attributes:
      label: What is the Event, CFP URL
      description: What is the event name and CFP URL?
      placeholder: ex. OSA 2022 Online - https..
    validations:
      required: true

  - type: checkboxes
    id: dates
    attributes:
      label: Last date to submit CFP
      description: Select appropriate label. Ex, "Sep22 - Includes CFPs closing by September 2022"
      options:
        - label: Sep 22
          required: false
        - label: Oct 22
          required: false
        - label: Nov 22
          required: false
        - label: Dec 22
          required: false
        - label: Jan 23
          required: false
        - label: Feb 23
          required: false
        - label: Mar 23
          required: false
